---
:concurrency: 5
:queues:
  - high_priority
  - default
  - low_priority
:scheduler:
  schedule_daily_invoice_job:
    enabled: false
    every: ["1d", first_in: "1m"]
    queue: default
    class: ScheduleDailyInvoiceJob
